 name: NullMob
 version: 1.0.2
 description: Disable AI of mobs
 author: InfoPaste

 main: me.InfoPaste.NullMob.Main

 commands:
    nullmob:
       description: NullMob main commands
       aliases: [nm]